--DEPARTMENT 
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY ) VALUES (dept_id_seq.nextval,'DEVELOPMENT','BILQU');
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY,CREATED_TS,UPDATED_TS ) VALUES (dept_id_seq.nextval,'QUALITY','BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY,CREATED_TS,UPDATED_TS ) VALUES (dept_id_seq.nextval,'ARCHITECTURE','BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

--CONTACT
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'MOBILE','2234567890');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'PHONE','1334567890');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'EMAIL','TEST@TEST.COM');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'EMAIL','TEST@TEST.COM');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'MAIL','1 state st, newyork');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'MAIL','2 state st, newyork');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'PHONE','5254567890');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'PHONE','7234767890');
INSERT INTO CONTACT (ID,CON_TYPE,CON_DTL) values (con_id_seq.nextval,'MOBILE','9234667890');

--EMPLOYEE
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,DEPT_ID) VALUES (emp_id_seq.nextval,'ANNA',31,10);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,DEPT_ID) VALUES (emp_id_seq.nextval,'EVE',38,20);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,UPDATED_BY,DEPT_ID) VALUES (emp_id_seq.nextval,'ADAM',38,'BILQU',10);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,UPDATED_BY,CREATED_TS,UPDATED_TS,DEPT_ID) VALUES (emp_id_seq.nextval,'MIA',31,'BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,30);


--EMPLOYEE_CONTACT
INSERT INTO EMPLOYEE_CONTACT (EMP_ID,CON_ID) VALUES  (1001,1);
INSERT INTO EMPLOYEE_CONTACT (EMP_ID,CON_ID) VALUES  (1001,2);
INSERT INTO EMPLOYEE_CONTACT (EMP_ID,CON_ID) VALUES  (1001,3);